local attackTable = {}

  --attackTable["Attack"] = {"Success","Failure"}
  attackTable["Shoot"] = {"Top Guard","Bottom Turtle"}
  attackTable["Pull Guard"] = {"Bottom Guard","Bottom Side Control"}
  attackTable["Foot Sweep"] = {"Top Side Control","Bottom Guard"}
  attackTable["Rear Naked Choke"] = {"Rear Naked Choke Offense","Top Rear Mount"}
  attackTable["Take the Back"] = {"Top Rear Mount","Bottom Guard"}
  attackTable["Armbar"] = {"Armbar Offense","Bottom Guard"}
  attackTable["Collar Choke"] = {"Collar Choke Offense","Top Mount"}
  attackTable["Go to Mount"] = {"Top Mount","Top Half Guard"}
  attackTable["Kimura"] = {"Kimura Offense","Top Side Control"}
  attackTable["Americana"] = {"Americana Offense","Top Side Control"}
  attackTable["Anaconda Choke"] = {"Anaconda Choke Offense","Top Turtle"}
  attackTable["Standing Knee Cut"] = {"Top Side Control","Top Half Guard"}
  attackTable["Leg Drag"] = {"Top Side Control","Top Guard"}
  attackTable["Double Underpass"] = {"Top Side Control","Top Guard"}
  attackTable["Underhook Pass"] = {"Top Side Control","Top Guard"}
  attackTable["Old School Sweep"] = {"Top Half Guard","Bottom Turtle"}
  attackTable["Deep Half Sweep"] = {"Top Guard","Bottom Half Guard"}
  attackTable["Triangle"] = {"Triangle Offense","Bottom Half Guard"}
  attackTable["Scissors Sweep"] = {"Top Mount","Bottom Half Guard"}
  attackTable["Omopalata"] = {"Omopalata Offense","Bottom Half Guard"}
  attackTable["Sit to Guard"] = {"Bottom Half Guard","Bottom Side Control"}
  attackTable["Turtle Sweep"] = {"Top Side Control","Bottom Rear Mount"}
  attackTable["Recover Guard"] = {"Bottom Guard","Bottom Side Control"}
  attackTable["Go to Knees"] = {"Bottom Turtle","Bottom Rear Mount"}
  attackTable["Recover Half Guard"] = {"Bottom Half Guard","Bottom Rear Mount"}
  attackTable["Trap and Roll"] = {"Top Guard","Bottom Mount"}
  attackTable["Slide Over Leg"] = {"Top Side Control","Bottom Mount"}
  attackTable["Recover Half Guard"] = {"Bottom Half Guard","Bottom Rear Mount"}
  attackTable["Squeeze Elbows"] = {"Submission","Top Rear Mount"}
  attackTable["Grind Neck"] = {"Submission","Top Rear Mount"}
  attackTable["Pull Arm"] = {"Top Guard","Tap"}
  attackTable["Cross Hands"] = {"Bottom Rear Mount","Tap"}
  attackTable["Crank the Arm"] = {"Submission","Bottom Guard"}
  attackTable["Push With Legs"] = {"Submission","Bottom Guard"}
  attackTable["Grab Bicep"] = {"Top Guard","Tap"}
  attackTable["Hitchhiker"] = {"Top Guard","Tap"}
  attackTable["Drive Forearms"] = {"Submission","Top Mount"}
  attackTable["Squeeze Elbows"] = {"Submission","Top Mount"}
  attackTable["Fight Hands"] = {"Bottom Mount","Tap"}
  attackTable["Break Base"] = {"Bottom Mount","Tap"}
  attackTable["Pull Arm Back"] = {"Submission","Top Side Control"}
  attackTable["Fake Pull"] = {"Submission","Top Side Control"}
  attackTable["Grip Belt"] = {"Bottom Side Control","Tap"}
  attackTable["Hide Arm"] = {"Bottom Side Control","Tap"}
  attackTable["Use Head"] = {"Submission","Top Mount"}
  attackTable["Pull Wrist In"] = {"Submission","Top Mount"}
  attackTable["Grab Hand"] = {"Bottom Mount","Tap"}
  attackTable["Break Base"] = {"Bottom Mount","Tap"}
  attackTable["Roll Through"] = {"Submission","Top Side Control"}
  attackTable["Squeeze Grip"] = {"Submission","Top Turtle"}
  attackTable["Grab Leg"] = {"Bottom Side Control","Tap"}
  attackTable["Keep Base"] = {"Bottom Turtle","Tap"}
  attackTable["Adjust Angle"] = {"Submission","Bottom Guard"}
  attackTable["Squeeze Legs"] = {"Submission","Bottom Guard"}
  attackTable["Create Posture"] = {"Top Guard","Tap"}
  attackTable["Fight the Angle"] = {"Top Guard","Tap"}
  attackTable["Pressure the Shoulder"] = {"Submission","Top Guard"}
  attackTable["Drag Hips Out"] = {"Submission","Top Guard"}
  attackTable["Roll Through"] = {"Bottom Guard","Tap"}
  attackTable["Posture Up"] = {"Top Guard","Tap"}


return attackTable