local attackTable = {}

  --attackTable["Attack"] = {"Success","Failure"}
  attackTable["Shoot"] = {"Top Guard","Bottom Turtle",2}
  attackTable["Pull Guard"] = {"Bottom Guard","Bottom Side Control",0}
  attackTable["Foot Sweep"] = {"Top Side Control","Bottom Guard",0}
  attackTable["Rear Naked Choke"] = {"Rear Naked Choke Offense","Top Rear Mount",0}
  attackTable["Take the Back"] = {"Top Rear Mount","Bottom Guard",4}
  attackTable["Armbar"] = {"Armbar Offense","Bottom Guard",0}
  attackTable["Collar Choke"] = {"Collar Choke Offense","Top Mount",0}
  attackTable["Go to Mount"] = {"Top Mount","Top Half Guard",4}
  attackTable["Kimura"] = {"Kimura Offense","Top Side Control",0}
  attackTable["Americana"] = {"Americana Offense","Top Side Control",0}
  attackTable["Anaconda Choke"] = {"Anaconda Choke Offense","Top Turtle",0}
  attackTable["Standing Knee Cut"] = {"Top Side Control","Top Half Guard",3}
  attackTable["Leg Drag"] = {"Top Side Control","Top Guard",3}
  attackTable["Double Underpass"] = {"Top Side Control","Top Guard",3}
  attackTable["Underhook Pass"] = {"Top Side Control","Top Guard",3}
  attackTable["Sit Thru Pass"] = {"Top Side Control","Top Guard",3}
  attackTable["Old School Sweep"] = {"Top Half Guard","Bottom Turtle",2}
  attackTable["Deep Half Sweep"] = {"Top Guard","Bottom Half Guard",2}
  attackTable["Triangle"] = {"Triangle Offense","Bottom Half Guard",0}
  attackTable["Scissors Sweep"] = {"Top Mount","Bottom Half Guard",2}
  attackTable["Omopalata"] = {"Omopalata Offense","Bottom Half Guard",0}
  attackTable["Sit to Guard"] = {"Bottom Half Guard","Bottom Side Control",0}
  attackTable["Turtle Sweep"] = {"Top Side Control","Bottom Rear Mount",0}
  attackTable["Recover Guard"] = {"Bottom Guard","Bottom Side Control",0}
  attackTable["Go to Knees"] = {"Bottom Turtle","Bottom Rear Mount",0}
  attackTable["Recover Half Guard"] = {"Bottom Half Guard","Bottom Rear Mount",0}
  attackTable["Trap and Roll"] = {"Top Guard","Bottom Mount",0}
  attackTable["Slide Over Leg"] = {"Top Side Control","Bottom Mount",3}
  attackTable["Recover Half Guard"] = {"Bottom Half Guard","Bottom Rear Mount",0}
  attackTable["Squeeze Elbows"] = {"Submission","Top Rear Mount",0}
  attackTable["Grind Neck"] = {"Submission","Top Rear Mount",0}
  attackTable["Pull Arm"] = {"Top Guard","Tap",0}
  attackTable["Cross Hands"] = {"Bottom Rear Mount","Tap",0}
  attackTable["Crank the Arm"] = {"Submission","Bottom Guard",0}
  attackTable["Push With Legs"] = {"Submission","Bottom Guard",0}
  attackTable["Grab Bicep"] = {"Top Guard","Tap",0}
  attackTable["Hitchhiker"] = {"Top Guard","Tap",0}
  attackTable["Drive Forearms"] = {"Submission","Top Mount",0}
  attackTable["Squeeze Elbows"] = {"Submission","Top Mount",0}
  attackTable["Fight Hands"] = {"Bottom Mount","Tap",0}
  attackTable["Break Base"] = {"Bottom Mount","Tap",0}
  attackTable["Pull Arm Back"] = {"Submission","Top Side Control",0}
  attackTable["Fake Pull"] = {"Submission","Top Side Control",0}
  attackTable["Grip Belt"] = {"Bottom Side Control","Tap",0}
  attackTable["Hide Arm"] = {"Bottom Side Control","Tap",0}
  attackTable["Use Head"] = {"Submission","Top Mount",0}
  attackTable["Pull Wrist In"] = {"Submission","Top Mount",0}
  attackTable["Grab Hand"] = {"Bottom Mount","Tap",0}
  attackTable["Break Base"] = {"Bottom Mount","Tap",0}
  attackTable["Roll Through"] = {"Submission","Top Side Control",0}
  attackTable["Squeeze Grip"] = {"Submission","Top Turtle",0}
  attackTable["Grab Leg"] = {"Bottom Side Control","Tap",0}
  attackTable["Keep Base"] = {"Bottom Turtle","Tap",0}
  attackTable["Adjust Angle"] = {"Submission","Bottom Guard",0}
  attackTable["Squeeze Legs"] = {"Submission","Bottom Guard",0}
  attackTable["Create Posture"] = {"Top Guard","Tap",0}
  attackTable["Fight the Angle"] = {"Top Guard","Tap",0}
  attackTable["Pressure the Shoulder"] = {"Submission","Top Guard",0}
  attackTable["Drag Hips Out"] = {"Submission","Top Guard",0}
  attackTable["Roll Through"] = {"Bottom Guard","Tap",0}
  attackTable["Posture Up"] = {"Top Guard","Tap",0}



return attackTable