local character = {}
  --Format   character["Position Name"] = {{Strong Attack Strength,Technical Attack Strength},{List of attack options}} 
  character["Standing"] = {{4,7},{"Shoot","Pull Guard","Foot Sweep"}}
  character["Top Rear Mount"] = {{4,7},{"Rear Naked Choke","Armbar"}}
  character["Top Mount"] = {{4,7},{"Take the Back","Armbar","Collar Choke"}}
  character["Top Side Control"] = {{4,7},{"Go to Mount","Kimura","Americana"}}
  character["Top Turtle"] = {{4,7},{"Take the Back","Anaconda Choke"}}
  character["Top Guard"] = {{4,7},{"Standing Knee Cut","Leg Drag","Double Underpass"}}
  character["Top Half Guard"] = {{4,7},{"Underhook Pass","Sit Thru Pass"}}
  character["Bottom Half Guard"] = {{4,7},{"Old School Sweep","Deep Half Sweep"}}
  character["Bottom Guard"] = {{4,7},{"Triangle","Scissors Sweep","Omopalata"}}
  character["Bottom Turtle"] = {{4,7},{"Sit to Guard","Turtle Sweep"}}
  character["Bottom Side Control"] = {{4,7},{"Recover Guard","Go to Knees"}}
  character["Bottom Mount"] = {{4,7},{"Recover Half Guard","Trap and Roll"}}
  character["Bottom Rear Mount"] = {{4,7},{"Slide Over Leg","Recover Half Guard"}}
  character["Rear Naked Choke Offense"] = {{4,7},{"Squeeze Elbows","Grind Neck"}}
  character["Rear Naked Choke Defense"] = {{4,7},{"Pull Arm","Cross Hands"}}
  character["Armbar Offense"] = {{4,7},{"Crank the Arm","Push With Legs"}}
  character["Armbar Defense"] = {{4,7},{"Grab Bicep","Hitchhiker"}}
  character["Collar Choke Offense"] = {{4,7},{"Drive Forearms","Squeeze Elbows"}}
  character["Collar Choke Defense"] = {{4,7},{"Fight Hands","Break Base"}}
  character["Kimura Offense"] = {{4,7},{"Pull Arm Back","Fake Pull"}}
  character["Kimura Defense"] = {{4,7},{"Grip Belt","Hide Arm"}}
  character["Americana Offense"] = {{4,7},{"Use Head","Pull Wrist In"}}
  character["Americana Defense"] = {{4,7},{"Grab Hand","Break Base"}}
  character["Anaconda Choke Offense"] = {{4,7},{"Roll Through","Squeeze Grip"}}
  character["Anaconda Choke Defense"] = {{4,7},{"Grab Leg","Keep Base"}}
  character["Triangle Offense"] = {{4,7},{"Adjust Angle","Squeeze Legs"}}
  character["Triangle Defense"] = {{4,7},{"Create Posture","Fight the Angle"}}
  character["Omopalata Offense"] = {{4,7},{"Pressure the Shoulder","Drag Hips Out"}}
  character["Omopalata Defense"] = {{4,7},{"Roll Through","Posture Up"}}
  character["Submission"] = {{0,0},{"",""}}
  character["Tap"] = {{0,0},{"",""}}
return character