local character = {}
  --Format   character["Position Name"] = {{Strong Attack Strength,Technical Attack Strength},{List of attack options}} 
  character["Standing"] = {{1,5},{"Shoot","Pull Guard","Foot Sweep"}}
  character["Top Rear Mount"] = {{2,6},{"Rear Naked Choke","Armbar"}}
  character["Top Mount"] = {{3,7},{"Take the Back","Armbar","Collar Choke"}}
  character["Top Side Control"] = {{4,8},{"Go to Mount","Kimura","Americana"}}
  character["Top Turtle"] = {{5,9},{"Take the Back","Anaconda Choke"}}
  character["Top Guard"] = {{6,8},{"Standing Knee Cut","Leg Drag","Double Underpass"}}
  character["Top Half Guard"] = {{7,7},{"Underhook Pass","Sit Thru Pass"}}
  character["Bottom Half Guard"] = {{8,6},{"Old School Sweep","Deep Half Sweep"}}
  character["Bottom Guard"] = {{9,5},{"Triangle","Scissors Sweep","Omopalata"}}
  character["Bottom Turtle"] = {{8,4},{"Sit to Guard","Turtle Sweep"}}
  character["Bottom Side Control"] = {{7,3},{"Recover Guard","Go to Knees"}}
  character["Bottom Mount"] = {{6,2},{"Recover Half Guard","Trap and Roll"}}
  character["Bottom Rear Mount"] = {{5,1},{"Slide Over Leg","Recover Half Guard"}}
  character["Rear Naked Choke Offense"] = {{4,2},{"Squeeze Elbows","Grind Neck"}}
  character["Rear Naked Choke Defense"] = {{3,3},{"Pull Arm","Cross Hands"}}
  character["Armbar Offense"] = {{2,4},{"Crank the Arm","Push With Legs"}}
  character["Armbar Defense"] = {{1,5},{"Grab Bicep","Hitchhiker"}}
  character["Collar Choke Offense"] = {{2,6},{"Drive Forearms","Squeeze Elbows"}}
  character["Collar Choke Defense"] = {{3,7},{"Fight Hands","Break Base"}}
  character["Kimura Offense"] = {{4,8},{"Pull Arm Back","Fake Pull"}}
  character["Kimura Defense"] = {{5,9},{"Grip Belt","Hide Arm"}}
  character["Americana Offense"] = {{6,8},{"Use Head","Pull Wrist In"}}
  character["Americana Defense"] = {{7,7},{"Grab Hand","Break Base"}}
  character["Anaconda Choke Offense"] = {{8,6},{"Roll Through","Squeeze Grip"}}
  character["Anaconda Choke Defense"] = {{9,5},{"Grab Leg","Keep Base"}}
  character["Triangle Offense"] = {{8,4},{"Adjust Angle","Squeeze Legs"}}
  character["Triangle Defense"] = {{7,3},{"Create Posture","Fight the Angle"}}
  character["Omopalata Offense"] = {{6,2},{"Pressure the Shoulder","Drag Hips Out"}}
  character["Omopalata Defense"] = {{5,1},{"Roll Through","Posture Up"}}
  character["Submission"] = {{0,0},{"",""}}
  character["Tap"] = {{0,0},{"",""}}
  character["Standing Defense"] = 5
  character["Guard Passing Defense"] = 5
  character["Guard Defense"] = 5
  character["Top Defense"] = 5
  character["Bottom Defense"] = 5
  character["Submission Defense"] = 5
  
return character