local opponent = {}
  --Format   opponent["Position Name"] = {{Strong Attack Strength,Technical Attack Strength},{List of attack options}} 
  opponent["Standing"] = {{1,10},{"Shoot","Pull Guard","Foot Sweep"}}
  opponent["Top Rear Mount"] = {{2,5},{"Rear Naked Choke","Armbar"}}
  opponent["Top Mount"] = {{3,5},{"Take the Back","Armbar","Collar Choke"}}
  opponent["Top Side Control"] = {{4,5},{"Go to Mount","Kimura","Americana"}}
  opponent["Top Turtle"] = {{5,5},{"Take the Back","Anaconda Choke"}}
  opponent["Top Guard"] = {{6,5},{"Standing Knee Cut","Leg Drag","Double Underpass"}}
  opponent["Top Half Guard"] = {{7,5},{"Underhook Pass","Sit Thru Pass"}}
  opponent["Bottom Half Guard"] = {{8,5},{"Old School Sweep","Deep Half Sweep"}}
  opponent["Bottom Guard"] = {{9,5},{"Triangle","Scissors Sweep","Omopalata"}}
  opponent["Bottom Turtle"] = {{8,5},{"Sit to Guard","Turtle Sweep"}}
  opponent["Bottom Side Control"] = {{7,5},{"Recover Guard","Go to Knees"}}
  opponent["Bottom Mount"] = {{6,5},{"Recover Half Guard","Trap and Roll"}}
  opponent["Bottom Rear Mount"] = {{5,5},{"Slide Over Leg","Recover Half Guard"}}
  opponent["Rear Naked Choke Offense"] = {{4,5},{"Squeeze Elbows","Grind Neck"}}
  opponent["Rear Naked Choke Defense"] = {{3,5},{"Pull Arm","Cross Hands"}}
  opponent["Armbar Offense"] = {{2,5},{"Crank the Arm","Push With Legs"}}
  opponent["Armbar Defense"] = {{1,5},{"Grab Bicep","Hitchhiker"}}
  opponent["Collar Choke Offense"] = {{2,5},{"Drive Forearms","Squeeze Elbows"}}
  opponent["Collar Choke Defense"] = {{3,5},{"Fight Hands","Break Base"}}
  opponent["Kimura Offense"] = {{4,5},{"Pull Arm Back","Fake Pull"}}
  opponent["Kimura Defense"] = {{5,5},{"Grip Belt","Hide Arm"}}
  opponent["Americana Offense"] = {{6,5},{"Use Head","Pull Wrist In"}}
  opponent["Americana Defense"] = {{7,5},{"Grab Hand","Break Base"}}
  opponent["Anaconda Choke Offense"] = {{8,5},{"Roll Through","Squeeze Grip"}}
  opponent["Anaconda Choke Defense"] = {{9,5},{"Grab Leg","Keep Base"}}
  opponent["Triangle Offense"] = {{8,5},{"Adjust Angle","Squeeze Legs"}}
  opponent["Triangle Defense"] = {{7,5},{"Create Posture","Fight the Angle"}}
  opponent["Omopalata Offense"] = {{6,5},{"Pressure the Shoulder","Drag Hips Out"}}
  opponent["Omopalata Defense"] = {{5,5},{"Roll Through","Posture Up"}}
  opponent["Submission"] = {{0,0},{"",""}}
  opponent["Tap"] = {{0,0},{"",""}}
return opponent