local opponent = {}
  --Format   opponent["Position Name"] = {{Strong Attack Strength,Technical Attack Strength},{List of attack options}} 
  opponent["Standing"] = {{1,10},{"Shoot","Pull Guard","Foot Sweep"},3}
  opponent["Top Rear Mount"] = {{2,5},{"Rear Naked Choke","Armbar"},2}
  opponent["Top Mount"] = {{3,5},{"Take the Back","Armbar","Collar Choke"},3}
  opponent["Top Side Control"] = {{4,5},{"Go to Mount","Kimura","Americana"},3}
  opponent["Top Turtle"] = {{5,5},{"Take the Back","Anaconda Choke"},2}
  opponent["Top Guard"] = {{6,5},{"Standing Knee Cut","Leg Drag","Double Underpass"},3}
  opponent["Top Half Guard"] = {{7,5},{"Underhook Pass","Sit Thru Pass"},2}
  opponent["Bottom Half Guard"] = {{8,5},{"Old School Sweep","Deep Half Sweep"},2}
  opponent["Bottom Guard"] = {{9,5},{"Triangle","Scissors Sweep","Omopalata"},3}
  opponent["Bottom Turtle"] = {{8,5},{"Sit to Guard","Turtle Sweep"},2}
  opponent["Bottom Side Control"] = {{7,5},{"Recover Guard","Go to Knees"},2}
  opponent["Bottom Mount"] = {{6,5},{"Recover Half Guard","Trap and Roll"},2}
  opponent["Bottom Rear Mount"] = {{5,5},{"Slide Over Leg","Recover Half Guard"},2}
  opponent["Rear Naked Choke Offense"] = {{4,5},{"Squeeze Elbows","Grind Neck"},2}
  opponent["Rear Naked Choke Defense"] = {{3,5},{"Pull Arm","Cross Hands"},2}
  opponent["Armbar Offense"] = {{2,5},{"Crank the Arm","Push With Legs"},2}
  opponent["Armbar Defense"] = {{1,5},{"Grab Bicep","Hitchhiker"},2}
  opponent["Collar Choke Offense"] = {{2,5},{"Drive Forearms","Squeeze Elbows"},2}
  opponent["Collar Choke Defense"] = {{3,5},{"Fight Hands","Break Base"},2}
  opponent["Kimura Offense"] = {{4,5},{"Pull Arm Back","Fake Pull"},2}
  opponent["Kimura Defense"] = {{5,5},{"Grip Belt","Hide Arm"},2}
  opponent["Americana Offense"] = {{6,5},{"Use Head","Pull Wrist In"},2}
  opponent["Americana Defense"] = {{7,5},{"Grab Hand","Break Base"},2}
  opponent["Anaconda Choke Offense"] = {{8,5},{"Roll Through","Squeeze Grip"},2}
  opponent["Anaconda Choke Defense"] = {{9,5},{"Grab Leg","Keep Base"},2}
  opponent["Triangle Offense"] = {{8,5},{"Adjust Angle","Squeeze Legs"},2}
  opponent["Triangle Defense"] = {{7,5},{"Create Posture","Fight the Angle"},2}
  opponent["Omopalata Offense"] = {{6,5},{"Pressure the Shoulder","Drag Hips Out"},2}
  opponent["Omopalata Defense"] = {{5,5},{"Roll Through","Posture Up"},2}
  opponent["Submission"] = {{0,0},{"",""},2}
  opponent["Tap"] = {{0,0},{"",""},2}
  opponent["Standing Defense"] = 5
  opponent["Guard Passing Defense"] = 5
  opponent["Guard Defense"] = 5
  opponent["Top Defense"] = 5
  opponent["Bottom Defense"] = 5
  opponent["Submission Defense"] = 5
return opponent